import time
print('logSystem: no logs')
time.sleep(4.5)
print('logSystem: ОТКЛЮЧЕНИЕ АР ПО НЕИСПРАВНОСТИ СТОПОРНЫЕ КРАНЫ ЗАКРЫТЫ')
time.sleep(3)
print('logSystem: СНИЖ ДАВЛ ВОДЫ ВПРЫСКА В КНД1')
time.sleep(2)
print('logSystem: НЕГОТОВНОСТЬ А3 А3-5 СУЗ')
time.sleep(1)
print('logSystem: НЕИСПР ИЗМЕРИТЕЛЬНОЙ ЧАСТИ А2')
time.sleep(0.1)
print('logSystem: РЕГУЛЯТОР П2-1332 ПОДКЛ ПРИ А3')
time.sleep(0.1)
print('logSystem: РЕГУЛЯТОР П1-1332 ПОДКЛ ПРИ А3')
time.sleep(0.1)
print('logSystem: РЕГУЛЯТОР П2-1332 В РЕЖИМЕ АВТ')
time.sleep(1.5)
print('logSystem: ОТКЛЮЧЕНИЕ АР ПО НЕИСПРАВНОСТИ')
time.sleep(3)
print('logSystem: РАЗГРУЗКА ТГ ПРИ А3-5')
time.sleep(0.7)
print('logSystem: А3СР СНИЖ ПЕРИОДА В ОСИ ДИАП')
time.sleep(0.3)
print('logSystem: А3М ПРЕВЫШ МОЩНОСТИ В ДИАП')
time.sleep(0.1)
print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 2УЗМ-1')
print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 2УЗМ-2')
print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 2УЗМ-3')
print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 2УЗМ-4')
print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 1УЗМ-1')
print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 1УЗМ-2')
print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 1УЗМ-3')
print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 1УЗМ-4')
print('logSystem: НЕИСПРАВН 1УЗМ-1')
time.sleep(1)
print('logSystem: НЕИСПРАВН 1УЗМ-2')
time.sleep(0.1)
print('logSystem: НЕИСПРАВН 1УЗМ-3')
print('logSystem: НЕИСПРАВН 1УЗМ-4')
print('logSystem: НЕИСПРАВН 2УЗМ-1')
print('logSystem: НЕИСПРАВН 2УЗМ-2')
print('logSystem: НЕИСПРАВН 2УЗМ-3')
print('logSystem: НЕИСПРАВН 2УЗМ-4')
time.sleep(0.7)
print('logSystem: НЕИСПРАВН ИЗМЕРИТ ЧАСТИ АР-2')
print('logSystem: НЕИСПРАВН ИЗМЕРИТ ЧАСТИ АР-1')
time.sleep(0.3)
print('logSystem: ОТКЛОНЕНИЕ АВАРИЙНОГО УРОВНЯ В БС')
time.sleep(1.8)
print('logSystem: ПРЕВЫШЕНО ДАВЛЕНИЕ В БС ПРАВЫЙ')
print('logSystem: ПРЕВЫШЕНО ДАВЛЕНИЕ В БС ЛЕВЫЙ')
time.sleep(2)
print('logSystem: НЕИСПРАВН ИЗМЕРИТ ЧАСТИ АР-2')
print('logSystem: НЕИСПРАВН ИЗМЕРИТ ЧАСТИ АР-1')
time.sleep(0.7)
print('logSystem: ОТКЛЮЧЕНИЕ АР ПО НЕИСПРАВНОСТИ')
time.sleep(0.3)
print('logSystem: ОТКЛОНЕНИЕ АВАРИЙНОГО УРОВНЯ В БС')
time.sleep(0.1)
while True:
    print('logSystem: НЕИСПРАВН 1УЗМ-3')
    print('logSystem: НЕИСПРАВН 1УЗМ-4')
    print('logSystem: НЕИСПРАВН 2УЗМ-1')
    print('logSystem: НЕИСПРАВН 2УЗМ-2')
    print('logSystem: НЕИСПРАВН 2УЗМ-3')
    print('logSystem: НЕИСПРАВН 2УЗМ-4')
    print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 2УЗМ-1')
    print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 2УЗМ-2')
    print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 2УЗМ-3')
    print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 2УЗМ-4')
    print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 1УЗМ-1')
    print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 1УЗМ-2')
    print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 1УЗМ-3')
    print('logSystem: ПРЕВЫШЕН N АВАРИЙНЫЙ 1УЗМ-4')
